# Generated by Django 3.2.25 on 2024-11-07 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='inventory.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='labels',
            field=models.ManyToManyField(related_name='items', to='inventory.Label'),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_uid', models.CharField(blank=True, help_text='Composite unique identifier: sender_email:folder:imap_uid', max_length=255, null=True, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('sender', models.EmailField(max_length=254)),
                ('recipients', models.JSONField(help_text='List of email addresses')),
                ('body', models.TextField()),
                ('thread_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sent_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='inventory.item')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('EMAIL', 'From Email'), ('UPLOAD', 'Manual Upload'), ('API', 'API Upload')], default='UPLOAD', help_text='Source of the attachment', max_length=20)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='inventory.email')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='qrcode',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_qr_code'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['sender'], name='inventory_e_sender_cd568e_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['sent_at'], name='inventory_e_sent_at_a5fa03_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['thread_id'], name='inventory_e_thread__0beb1d_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['email_uid'], name='inventory_e_email_u_eefdf2_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['content_type'], name='inventory_a_content_ec15d5_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['created_at'], name='inventory_a_created_18257c_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['source'], name='inventory_a_source_79817b_idx'),
        ),
    ]
