# Generated by Django 3.2.25 on 2024-11-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes'),
        ),
    ]
