# Generated by Django 3.2.25 on 2024-12-03 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20241107_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIImgdescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, default='', max_length=4096, null=True)),
                ('payload', models.CharField(blank=True, default='', max_length=4096, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AIdescription', to='inventory.attachment')),
            ],
        ),
        migrations.CreateModel(
            name='AIdescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, default='', max_length=4096, null=True)),
                ('payload', models.CharField(blank=True, default='', max_length=4096, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AIdescription', to='inventory.item')),
            ],
        ),
    ]
