# Generated by Django 3.2.25 on 2024-12-03 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_aidescription_aiimgdescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiimgdescription',
            old_name='item',
            new_name='attachment',
        ),
    ]
