# Generated by Django 3.2.25 on 2024-12-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_item_aiimgdescription_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ai_aggregated_description',
            field=models.TextField(blank=True, help_text='Aggregated AI descriptions from all attachments', null=True),
        ),
    ]
