# Generated by Django 3.2.25 on 2024-12-10 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_ai_aggregated_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidescription',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_ai_descriptions', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='aiimgdescription',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_ai_descriptions', to='inventory.attachment'),
        ),
    ]
