# Generated by Django 3.2.25 on 2024-12-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20241210_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidescription',
            name='response',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='aiimgdescription',
            name='response',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
