# Generated by Django 3.2.25 on 2024-12-18 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20241212_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Listing categories',
            },
        ),
        migrations.CreateModel(
            name='ListingLBC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ordinateurs', 'Ordinateurs'), ('accessoires_informatique', 'Accessoires informatique'), ('tablettes_liseuses', 'Tablettes & Liseuses'), ('photo_audio_video', 'Photo, audio & vidéo'), ('telephones_objets_connectes', 'Téléphones & Objets connectés'), ('accessoires_telephone', 'Accessoires téléphone & Objets connectés')], default='ordinateurs', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings_lbc', to='inventory.item')),
            ],
        ),
    ]
